server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pp0alm?serverTimezone=GMT-5&allowMultiQueries=true
    username: root
    password: password  # my password
  jpa:
    hibernate:
      ddl-auto: create # Or create, create-drop, validate
    show-sql: true # Optional: to see the generated SQL in the console
    properties:
      hibernate:
        format_sql: true # Optional: to format the generated SQL
  sql:
    init:
      mode: always

jwt:
  secret: ThisIsASecretKeyForJWTsChangeMe
  expiration-ms: 3600000